--- #YAML:1.0
name:               MP3-Find
version:            0.07
abstract:           Search and sort MP3 files based on their ID3 tags
author:
    - Peter Eichman <peichamn@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:    0
    MP3::Info:     0
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
